export interface AreaSeed {
  readonly code: string;
  readonly name: string;
}

export interface EquipmentSeed {
  readonly area: string;
  readonly code: string | null;
  readonly description: string;
  readonly legacyId: number;
  readonly name: string;
}

export const areas = [
  { code: 'MANTENIMIENTO', name: 'Mantenimiento' },
  { code: 'ESTERILES', name: 'Estériles' },
  { code: 'LIQUIDOS-ORALES', name: 'Líquidos Orales' },
  { code: 'MATERIA-PRIMA', name: 'Materia Prima' },
  { code: 'DISPENSACION', name: 'Dispensación' },
  { code: 'SOLIDOS-III', name: 'Sólidos III' },
  { code: 'ACOND-NO-ESTERIL', name: 'Acond no estéril' },
  { code: 'SOLIDOS-II', name: 'Sólidos II' },
  { code: 'SOLIDOS-I', name: 'Sólidos I' },
  { code: 'SEMISOLIDOS', name: 'Semisólidos' },
  { code: 'CONTROL-CALIDAD', name: 'Control de calidad' },
] as const satisfies readonly AreaSeed[];

export const machines = [
  { legacyId: 1, name: 'Bramcor', code: 'MQ-24-46', area: 'Mantenimiento', description: 'Generación de Agua Purificada PW' },
  { legacyId: 2, name: 'Caldero Cleaver Brooks', code: 'MQ-24-42', area: 'Mantenimiento', description: 'Generación de vapor industrial' },
  { legacyId: 3, name: 'Compresor Schulz 3040', code: 'MQ-24-1', area: 'Mantenimiento', description: 'Aire comprimido' },
  { legacyId: 4, name: 'Compresor Schulz 4050', code: 'MQ-24-49', area: 'Mantenimiento', description: 'Aire comprimido' },
  { legacyId: 5, name: 'Compresor Somar', code: 'MQ-24-82', area: 'Mantenimiento', description: 'Aire comprimido' },
  { legacyId: 6, name: 'Letzner', code: 'MQ-24-47', area: 'Mantenimiento', description: 'Generación de Agua para Inyectables WFI' },
  { legacyId: 7, name: 'Chiller Aermec', code: 'MQ-24-65', area: 'Mantenimiento', description: 'Agua fría' },
  { legacyId: 8, name: 'Loop PW', code: 'EQ-24-41', area: 'Mantenimiento', description: 'Distribución de Agua PW' },
  { legacyId: 9, name: 'Loop WFI', code: 'EQ-24-58', area: 'Mantenimiento', description: 'Distribución de Agua WFI' },
  { legacyId: 10, name: 'Intercambiador de calor Agua Caliente', code: 'EQ-24-51', area: 'Mantenimiento', description: 'Agua caliente' },
  { legacyId: 11, name: 'Autoclave #1', code: 'MQ-13-59', area: 'Estériles', description: 'Esterilización' },
  { legacyId: 12, name: 'Autoclave #2', code: 'MQ-13-60', area: 'Estériles', description: 'Esterilización' },
  { legacyId: 13, name: 'Autoclave #3', code: 'MQ-13-61', area: 'Estériles', description: 'Esterilización' },
  { legacyId: 14, name: 'Tanque Baño María', code: 'MQ-11-14', area: 'Líquidos Orales', description: 'Producción de Líquidos Orales' },
  { legacyId: 15, name: 'Tanque Reactor 1000L', code: 'MQ-11-1', area: 'Líquidos Orales', description: 'Producción de Líquidos Orales' },
  { legacyId: 16, name: 'Tanque Reactor 500L', code: 'MQ-11-2', area: 'Líquidos Orales', description: 'Producción de Líquidos Orales' },
  { legacyId: 17, name: 'Tanque Reactor Curadil', code: 'MQ-12-11', area: 'Líquidos Orales', description: 'Producción de Líquidos Orales' },
  { legacyId: 18, name: 'Sistema de Alarmas', code: 'AL-01-M', area: 'Mantenimiento', description: 'Sensores de alarma en planta' },
  { legacyId: 19, name: 'Tanque Reactor Estériles', code: 'MQ-13-53', area: 'Estériles', description: 'Producción de Estériles' },
  { legacyId: 20, name: 'UTA #1 (MUESTREO)', code: 'MQ-8-4', area: 'Materia Prima', description: 'HVAC' },
  { legacyId: 21, name: 'UTA #2 (DISPENSACIÓN)', code: 'MQ-24-3', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 22, name: 'UEA #2 (SÓLIDOS III)', code: 'MQ-24-4', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 23, name: 'UTA #3 (LÍQUIDOS ORALES)', code: 'MQ-24-48', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 24, name: 'UTA #4 (ESTÉRILES)', code: 'MQ-24-52', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 25, name: 'UTA #5 (LAVADO ESTÉRIL)', code: 'MQ-24-53', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 26, name: 'UTA #6 (CANULADO)', code: 'MQ-24-54', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 27, name: 'UTA #7 (SÓLIDOS II)', code: 'MQ-24-5', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 28, name: 'UEA #7 (SÓLIDOS II)', code: 'MQ-24-6', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 29, name: 'UTA #8 (AGUA)', code: 'MQ-24-100', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 30, name: 'UEA #8 (AGUA)', code: 'MQ-24-101', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 31, name: 'UTA #9 (ACOND ESTÉRIL)', code: 'MQ-24-7', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 32, name: 'UEA #9 (ACOND ESTÉRIL)', code: 'MQ-24-8', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 33, name: 'UTA #10 (CONTROL DE CALIDAD)', code: 'MQ-24-9', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 34, name: 'UEA #10 (CONTROL DE CALIDAD)', code: 'MQ-24-10', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 35, name: 'UTA #11 (MICROBIOLOGÍA)', code: 'MQ-24-11', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 36, name: 'UEA #11 (MICROBIOLOGÍA)', code: 'MQ-24-12', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 37, name: 'UTA #12 (SÓLIDOS I)', code: 'MQ-24-13', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 38, name: 'UEA #12 (SÓLIDOS I)', code: 'MQ-24-14', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 39, name: 'UTA #13 (SEMISÓLIDOS)', code: 'MQ-24-15', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 40, name: 'UEA #13 (SEMISÓLIDOS)', code: 'MQ-24-16', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 41, name: 'UTA #14 (ESTABILIDAD)', code: 'MQ-28-1', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 42, name: 'UTA #15 (ACOND PRIM)', code: 'MQ-24-59', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 43, name: 'UEA #15 (ACOND PRIM)', code: 'MQ-24-60', area: 'Mantenimiento', description: 'HVAC' },
  { legacyId: 44, name: 'Tanque Condensado', code: 'MQ-24-102', area: 'Mantenimiento', description: 'Recuperación de condensado' },
  { legacyId: 45, name: 'Ablandador de agua', code: 'EQ-24-43', area: 'Mantenimiento', description: 'Agua blanda para caldero y chiller' },
] as const satisfies readonly EquipmentSeed[];

export const devices = [
  { legacyId: 1, name: 'TH1_dosificado_esteriles_1', code: 'ESP32_Client01', area: 'Estériles', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 2, name: 'TH2_dosificado_esteriles_2', code: 'ESP32_Client02', area: 'Estériles', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 3, name: 'TH3_dosificado_liquidos_1', code: 'ESP32_Client03', area: 'Líquidos Orales', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 4, name: 'TH4_dosificado_lo_2', code: 'ESP32_Client04', area: 'Líquidos Orales', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 5, name: 'TH5_dispensado_esteril', code: 'ESP32_Client05', area: 'Dispensación', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 6, name: 'TH6_dispensado_no_esteril', code: 'ESP32_Client06', area: 'Dispensación', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 7, name: 'TH7_mezclado_s3', code: 'ESP32_Client07', area: 'Sólidos III', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 8, name: 'TH8_encapsulado', code: 'ESP32_Client08', area: 'Sólidos III', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 9, name: 'TH9_almacen_1_acond', code: 'ESP32_Client09', area: 'Acond no estéril', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 10, name: 'TH10_blisteado', code: 'ESP32_Client10', area: 'Sólidos II', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 11, name: 'TH11_mezclado_s2', code: 'ESP32_Client11', area: 'Sólidos II', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 12, name: 'TH12_suspensiones', code: 'ESP32_Client12', area: 'Sólidos II', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 13, name: 'TH13_recubrimieto_s2', code: 'ESP32_Client13', area: 'Sólidos II', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 14, name: 'TH14_mezclado_s1', code: 'ESP32_Client14', area: 'Sólidos I', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 15, name: 'TH15_secado', code: 'ESP32_Client15', area: 'Sólidos I', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 16, name: 'TH16_mezclado_efervescentes', code: 'ESP32_Client16', area: 'Sólidos I', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 17, name: 'TH17_comprimidora_6', code: 'ESP32_Client17', area: 'Sólidos I', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 18, name: 'TH18_foliadora_b', code: 'ESP32_Client18', area: 'Sólidos I', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 19, name: 'TH19_recubrimieto_s1', code: 'ESP32_Client19', area: 'Sólidos I', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 20, name: 'TH20_almacen_prod_granel', code: 'ESP32_Client20', area: 'Sólidos I', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 21, name: 'TH21_blistera_blipack', code: 'ESP32_Client21', area: 'Sólidos I', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 22, name: 'TH22_foliadora', code: 'ESP32_Client22', area: 'Sólidos I', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 23, name: 'TH23_dosificado_ovulos', code: 'ESP32_Client23', area: 'Semisólidos', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 24, name: 'TH24_dosificado_1', code: 'ESP32_Client24', area: 'Semisólidos', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 25, name: 'TH25_preparado_1', code: 'ESP32_Client25', area: 'Semisólidos', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 26, name: 'TH26_formadora_alveolos', code: 'ESP32_Client26', area: 'Semisólidos', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 27, name: 'TH27_preparado_2', code: 'ESP32_Client27', area: 'Semisólidos', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 28, name: 'TH28_dosificado_2', code: 'ESP32_Client28', area: 'Semisólidos', description: 'Monitoreo de TH en ambientes.' },
  { legacyId: 29, name: 'Estabilidad1', code: 'EQ-24-101', area: 'Control de calidad', description: 'Monitoreo ambiente de estabilidad sensor #1' },
  { legacyId: 30, name: 'Estabilidad2', code: 'EQ-24-102', area: 'Control de calidad', description: 'Monitoreo ambiente de estabilidad sensor #2' },
  { legacyId: 31, name: 'Estabilidad3', code: 'EQ-24-103', area: 'Control de calidad', description: 'Monitoreo ambiente de estabilidad sensor #3' },
  { legacyId: 32, name: 'Estabilidad4', code: 'EQ-24-104', area: 'Control de calidad', description: 'Monitoreo ambiente de estabilidad sensor #4' },
  { legacyId: 33, name: 'Estabilidad5', code: 'EQ-24-105', area: 'Control de calidad', description: 'Monitoreo ambiente de estabilidad sensor #5' },
  { legacyId: 34, name: 'Estabilidad6', code: 'EQ-24-106', area: 'Control de calidad', description: 'Monitoreo ambiente de estabilidad sensor #6' },
  { legacyId: 35, name: 'Estabilidad7', code: 'EQ-24-107', area: 'Control de calidad', description: 'Monitoreo ambiente de estabilidad sensor #7' },
  { legacyId: 36, name: 'Estabilidad8', code: 'EQ-24-108', area: 'Control de calidad', description: 'Monitoreo ambiente de estabilidad sensor #8' },
  { legacyId: 37, name: 'Estabilidad9', code: 'EQ-24-109', area: 'Control de calidad', description: 'Monitoreo ambiente de estabilidad sensor #9' },
  { legacyId: 38, name: 'Estabilidad10', code: 'EQ-24-110', area: 'Control de calidad', description: 'Monitoreo ambiente de estabilidad sensor #10' },
  { legacyId: 39, name: 'Estabilidad11', code: 'EQ-24-111', area: 'Control de calidad', description: 'Monitoreo ambiente de estabilidad sensor #11' },
  { legacyId: 40, name: 'Estabilidad12', code: 'EQ-24-112', area: 'Control de calidad', description: 'Monitoreo ambiente de estabilidad sensor #12' },
] as const satisfies readonly EquipmentSeed[];
